version: '2'
services:

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - elastic

volumes:
  data01:
    driver: local
#  data02:
#    driver: local

networks:
  elastic:
    driver: bridge